### ISSUE TITLE
Unknown project.version and lib.packaging

### ISSUE THREAD

**Issue by kzheludkov** [VladRodionov/carrot#239]
Suppose to add to properties?
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>11</java.version>
        <project.version>1.0.0</project.version>
        <lib.packaging>1.0.0</lib.packaging>
    </properties>

**Comment by VladRodionov** [comment]
You should run maven with:
mvn --settings settings.xml package. Please make sure you update settings.xml to your environment. I fixed the build in general. Working on packaging.

**Comment by VladRodionov** [comment]
What is your environment? Windows? Can you pull changes, check your settings.xml file and re-run build?

**Comment by VladRodionov** [comment]
Seems you can close this issue, Kostya?

**Comment by kzheludkov** [comment]
I am fine with resolution for this issue. 
I was able to build project on Mac and Ubuntu(on Windows) However, every time I need to change settings.xml as below. 
In my point of view that changes will make build more generic. So, dev just need to set JAVA_HOME instead update own copy of settings.xml and everything compile just fine.

For Mac profile
<JAVA_INCLUDE>-I${JAVA_HOME}/include -I${JAVA_HOME}/include/darwin</JAVA_INCLUDE>

For Linux profile
<JAVA_INCLUDE>-I${JAVA_HOME}/include -I${JAVA_HOME}/include/linux</JAVA_INCLUDE>

Otherwise we can close this.
LMN
