### ISSUE TITLE
[TASK] Fix Maven build

### ISSUE THREAD

**Issue by VladRodionov** [VladRodionov/carrot#242]
Issues with a current build:

1.  Uber jar is not created when `maven package`
2. Check and fix maven warnings for install, package
3. Remove unnecessary example module from uber jar (package)
4. Remove unused dependencies

**Comment by kzheludkov** [comment]
uder jar has problem with so lib. At this time I created assembly with all dependencies in dist module.
removed unused dependencies and version conflicts
